### ISSUE TITLE
How does it scale?

### ISSUE THREAD

**Issue by schamberg97** [rooseveltframework/express-php-view-engine#28]
Hey there! Just wanted to ask, how well this module scales? Do I understand correctly that you just fork a new process whenever `res.render` occurs, which loads `loader.php`, which in turn parses JSON that you pass to it and then processes user’s PHP scripts? And do I understand correctly that it does not do any internal caching in `process.eng.NODE_ENV === “production”` mode, like many other templating engines do? Why would I prefer this to nginx + php?

**Comment by kethinov** [comment]
Sorry for the delayed response, somehow I didn't see a the email from GitHub and I only caught this while doing a backlog grooming of all the repos in this group.

The goal of this project is to get data originating from an Express server to trickle into a PHP script, which isn't something you can do with just nginx + php by itself. If you don't need data from an Express server, then nginx + php is probably better. I'm not convinced the implementation in this module is the best or more scalable way to do it; merely the best approach I could come up with at the time to get it working. Open to totally rewriting it with another approach some day if some better architecture is proposed. Though oddly it did seem faster than JS-based templating systems (e.g. ejs, pug, etc) in my quick testing, so who knows, maybe we're onto something here.

There is no caching outside of whatever caching that PHP may do on its own. Might be worth exploring how something like Memcached could be used alongside this, but it's not something I've given any thought to yet.
